import type { Metadata } from "next";
import "./globals.css";
import { PropsWithChildren } from "react";
import { Roboto } from "next/font/google";

export const metadata: Metadata = {
  title: "ScoopDash",
  description: "Generated by create next app",
  icons: [
    {
      url: "/apple-touch-icon.png",
      rel: "apple-touch-icon",
      sizes: "180x180",
      "type": "image/png"
    },
    {
      url: "/favicon-32x32.png",
      rel: "icon",
      sizes: "32x32",
      "type": "image/png"
    },
    {
      url: "/favicon-16x16.png",
      rel: "icon",
      sizes: "16x16",
      "type": "image/png"
    },
    {
      rel: "icon",
      "url": "/android-chrome-192x192.png",
      "sizes": "192x192",
      "type": "image/png"
    },
    {
      rel: "icon",
      "url": "/android-chrome-512x512.png",
      "sizes": "512x512",
      "type": "image/png"
    }
  ]
};


const roboto = Roboto({ weight: "400", subsets: ["latin"] });



export default function RootLayout({ children }: PropsWithChildren) {
  return (
    <html lang="en">
    <body
      className={`${roboto.className} max-w-full min-h-screen bg-brand-yellow text-brand-yellow-content grid grid-cols-1 grid-rows-[4rem,1fr]`}>
      {children}
    </body>
    </html>
  );
}
