import type { Metadata } from "next";
import "./globals.css";
import { PropsWithChildren } from "react";
import { Roboto } from "next/font/google";
import { RepositoryProvider } from "./RepositoryProvider";
import { PrismaClient } from "@prisma/client";

import {PostgressInterestedPeepRepository} from "@/InterestedPeepRepository";

export const metadata: Metadata = {
  title: "ScoopDash",
  description: "Generated by create next app",
  icons: [
    {
      url: "/apple-touch-icon.png",
      rel: "apple-touch-icon",
      sizes: "180x180",
      type: "image/png",
    },
    {
      url: "/favicon-32x32.png",
      rel: "icon",
      sizes: "32x32",
      type: "image/png",
    },
    {
      url: "/favicon-16x16.png",
      rel: "icon",
      sizes: "16x16",
      type: "image/png",
    },
    {
      rel: "icon",
      url: "/android-chrome-192x192.png",
      sizes: "192x192",
      type: "image/png",
    },
    {
      rel: "icon",
      url: "/android-chrome-512x512.png",
      sizes: "512x512",
      type: "image/png",
    },
  ],
};

const roboto = Roboto({ weight: "400", subsets: ["latin"] });

export default function RootLayout({ children }: PropsWithChildren) {
  const prisma = new PrismaClient({
    datasources: {
      db: {
        url: process.env.DATABASE_URL,
      },
    },
  });

  const repo = new PostgressInterestedPeepRepository(prisma);

  return (
    <html lang="en">
      <body
        className={`${roboto.className} grid min-h-screen max-w-full grid-cols-1 grid-rows-[4rem,1fr] bg-brand-yellow text-brand-yellow-content`}
      >
        <RepositoryProvider repository={repo}>
        {children}
        </RepositoryProvider>
      </body>
    </html>
  );
}
