// import { Pool } from 'pg'
// import { PrismaPg } from '@prisma/adapter-pg'
// import { PrismaClient } from '@prisma/client'

// const connectionString = `${process.env.DATABASE_URL}`

// const pool = new Pool({ connectionString })
// const adapter = new PrismaPg(pool)
// const prisma = new PrismaClient({ adapter })

// export const getServerSideProps = async () => {
//   const feed = await prisma.interestedUser.deleteMany({});
//   return { props: { feed } }
// }

import type { Metadata } from "next";
import { Lobster_Two } from "next/font/google";
import { FormEvent, useState } from 'react';

export const metadata: Metadata = {
  title: "ScoopDash",
  description: "Generated by create next app",
};

const lobsterTwo = Lobster_Two({ subsets: ["latin"], weight: "700" });


export default function Home() {
  const [count, setCount] = useState(0);

  const handleSubmit = (event: FormEvent<HTMLFormElement>) => {
    event.preventDefault();
    setCount(count + 1);

  };
  return (
    <>
      <nav
        className={
          "m-0 bg-brand-blue p-4 text-brand-blue-content drop-shadow-sm"
        }
      >
        <h1 className={`text-2xl ${lobsterTwo.className}`}>🍦 ScoopDash</h1>
      </nav>
      <main className="flex h-full flex-grow flex-col items-center justify-around">
        <div className="m-10 flex flex-col gap-4 rounded bg-brand-purple p-10">
          <h2 className={`text-center text-3xl ${lobsterTwo.className}`}>
            Coming Soon!
          </h2>
          <h3 className={"text-center"}>Interested Peeps: {count}</h3>
          <form onSubmit={handleSubmit}>
            <label htmlFor="email">visitors email</label>
            <input type="email" id="email" name="visitors email" />
            
            <button type="submit">Submit</button>
          </form>
        </div>
      </main>
    </>
  );
}
