// import { Pool } from 'pg'
// import { PrismaPg } from '@prisma/adapter-pg'
// import { PrismaClient } from '@prisma/client'

// const connectionString = `${process.env.DATABASE_URL}`

// const pool = new Pool({ connectionString })
// const adapter = new PrismaPg(pool)
// const prisma = new PrismaClient({ adapter })

// export const getServerSideProps = async () => {
//   const feed = await prisma.interestedUser.deleteMany({});
//   return { props: { feed } }
// }


import type { Metadata } from "next";
import { Lobster_Two } from "next/font/google";

export const metadata: Metadata = {
  title: "ScoopDash",
  description: "Generated by create next app",
};


const lobsterTwo = Lobster_Two({ subsets: ["latin"], weight: "700" });


export default function Home() {
  return (
    <>
      <nav className={"drop-shadow-sm bg-brand-blue text-brand-blue-content m-0 p-4"}>
        <h1 className={`text-2xl ${lobsterTwo.className}`}>🍦 ScoopDash</h1>
      </nav>
      <main className="flex-grow flex flex-col items-center h-full justify-around">
        <div className="flex flex-col gap-4 bg-brand-purple m-10 p-10 rounded">
          <h2 className={`text-center text-3xl ${lobsterTwo.className}`}>Coming Soon!</h2>
          <h3 className={"text-center"}>Interested Peeps: 0</h3>
        </div>
      </main>
    </>
  );
}
